name: Downstream Trigger

on:
  pull_request:
    # branches:
    #   - main

jobs:
  run-py-pytest:
    name: Run Python Pytest Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-py-pytest.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-py-unittest:
    name: Run Python Unittest Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-py-unittest.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-cs-xunit:
    name: Run C# XUnit Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-cs-xunit.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-cs-nunit:
    name: Run C# NUnit Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-cs-nunit.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-js-jest:
    name: Run JavaScript JEST Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-js-jest.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-js-mocha:
    name: Run JavaScript Mocha Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-js-mocha.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest

  run-js-storybook:
    name: Run JavaScript Storybook Comparison
    # No explicit check_pr_source dependency, tests should run for any PR to main.
    # If tests pass and PR is from dev, then downstream will run.
    uses: JamesonRGrieve/Workflows/.github/workflows/test-js-storybook.yml@main
    with:
      # PR is to main, so compare PR branch against main.
      target_branch_to_compare: ${{ github.base_ref }} # This will be 'main'
    permissions:
      contents: write # For lint within pytest
